### ISSUE TITLE
chromatin states in mouse (mm)

### ISSUE THREAD

**Issue by gireeshkbogu** [gireeshkbogu/chromatin_states_chromHMM_mm9#1]
![screenshot-4](https://cloud.githubusercontent.com/assets/3885659/11807271/09976574-a319-11e5-82be-907739d817c3.png)

**Comment by chrisclarkson** [comment]
Is there any official documentation on why these different states are given names like 'Strong Enhancer, Weak Enhancer'? I'm guessing there is a lot of information in human Chromhmm tracks that elaborate on what a 'Strong vs weak enhancer is'. However I cannot seem to find any documentation on mice? 
Also is there a graph that shows which states can transition into other types of states (such as the standard output PNG that comes from a ChromHMM analysis e.g. 'transitions_[state_number].png')?

**Comment by gireeshkbogu** [comment]
I suggest you read this https://www.nature.com/articles/nmeth.1673 and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3577932/. The procedure is same in human or mouse.

**Comment by chrisclarkson** [comment]
Thank you so much. Is there any information on how the states on your GitHub page as to how the states transition between one another?

Chris

________________________________

**Comment by gireeshkbogu** [comment]
Hi Chris, you have your answers in the supplemental material of the links I gave you earlier. Please take your time and understand the observations in those papers. If you have any specific questions about how the method works, you should email to Jason Ernst (who is the first author of those papers and developer of chromHMM). I provided his lab page link in the readme file. Hope that helps.
